// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/:slug": {
    params: {
      "slug": string;
    };
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/projects" | "/projects/:slug" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "routes/projects-detail.tsx": {
    id: "routes/projects-detail";
    page: "/projects/:slug";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};