export const projects = [
  {
    id: 1,
    name: "Address Book",
    description: "A simple address book application to manage contacts.",
    image: "../images/projects/address-book.png",
    link: "https://address-book.cakrasera.com",
    github: "https://github.com/CakraSera/address-book",
    tags: ["JavaScript", "HTML", "Tailwind CSS"],
    date: "2023-01-01",
    status: "completed",
    type: "web",
    technologies: [
      { name: "JavaScript", icon: "https://via.placeholder.com/20" },
      { name: "HTML", icon: "https://via.placeholder.com/20" },
      { name: "Tailwind CSS", icon: "https://via.placeholder.com/20" },
    ],
    features: [
      "Add, edit, and delete contacts",
      "Search and filter contacts",
      "Responsive design",
    ],
    challenges: [
      "Implementing local storage for data persistence",
      "Creating a responsive layout",
      "Handling user input validation",
    ],
    learnings: [
      "Improved JavaScript skills",
      "Learned about local storage",
      "Gained experience with responsive design",
    ],
  },
  {
    id: 2,
    name: "Kanban Board",
    description: "A kanban board application to manage tasks and projects.",
    image: "../images/projects/kanban-board.png",
    link: "https://kanban-board.cakrasera.com",
    github: "https://github.com/CakraSera/kanban",
    tags: ["React", "Tailwind", "Shadcn UI"],
    date: "2023-02-01",
    status: "in-progress",
    type: "web",
    technologies: [
      { name: "React", icon: "https://via.placeholder.com/20" },
      { name: "Tailwind CSS", icon: "https://via.placeholder.com/20" },
      { name: "Shadcn UI", icon: "https://via.placeholder.com/20" },
    ],
    features: [
      "Create, edit, and delete tasks",
      "Drag and drop functionality",
      "Filter tasks by status",
    ],
    challenges: [
      "Implementing drag and drop functionality",
      "Managing state with React",
      "Creating a user-friendly interface",
    ],
    learnings: [
      "Improved React skills",
      "Learned about state management",
      "Gained experience with drag and drop functionality",
    ],
  },
  {
    id: 3,
    name: "Narai Coder",
    description:
      "A personal website comunity for sharing knowledge and resources.",
    image: "../images/projects/narai-coder.jpg",
    link: "https://naraicoder.org",
    github: "https://github.com/Hayolox/NaraiCoder",
    tags: ["html", "css", "bootstrap"],
    date: "2022-03-01",
    status: "completed",
    type: "web",
    technologies: [
      { name: "HTML", icon: "https://via.placeholder.com/20" },
      { name: "CSS", icon: "https://via.placeholder.com/20" },
      { name: "Bootstrap", icon: "https://via.placeholder.com/20" },
    ],
    features: [
      "User registration and login",
      "Post creation and commenting",
      "Responsive design",
    ],
    challenges: [
      "Implementing user authentication",
      "Creating a responsive layout",
      "Handling user input validation",
    ],
    learnings: [
      "Improved HTML and CSS skills",
      "Learned about user authentication",
    ],
  },
];

export const workExperience = [
  {
    id: 1,
    companyName: "DataOn (PT Indodev Niaga Internet)",
    position: "Implementation Consultant Jr",
    logo: "./images/dataon-logo.png",
    startDate: new Date("2024-05-27"),
    endDate: new Date(),
    technologies: [
      { name: "CFML", icon: "https://via.placeholder.com/20" },
      { name: "React JS", icon: "https://via.placeholder.com/20" },
      { name: "HTML", icon: "https://via.placeholder.com/20" },
      { name: "CSS", icon: "https://via.placeholder.com/20" },
      { name: "JavaScript", icon: "https://via.placeholder.com/20" },
      { name: "Git", icon: "https://via.placeholder.com/20" },
    ],
    jobDescription: [
      "Developing and implementing custom web applications using React.js, CFML, HTML, CSS, and JavaScript to meet specific client requirements and maintained web applications",
      "Collaborating closely with Implementation Consultants to ensure deliverables align with client expectations and business objectives",
      "Maintaining consistent code quality through Git version control, Gitlab for CI/CD, and SonarQube for code quality assurance",
      "Adapting and extending DataOn's core applications to create customized solutions for enterprise clients",
      "Troubleshooting and resolving technical issues to ensure smooth application deployment and operation",
      "Consistently achieving high performance ratings, with a current score of 4.32/5",
    ],
  },
  {
    id: 2,
    companyName: "PT. QATROS TEKNOLOGI NUSANTARA",
    position: "Frontend Web Engineer",
    logo: "./images/qatros-logo.png",
    startDate: new Date("2022-08-01"),
    endDate: new Date("2022-12-01"),
    technologies: [
      { name: "Nuxt.js", icon: "https://via.placeholder.com/20" },
      { name: "Vue.js", icon: "https://via.placeholder.com/20" },
      { name: "Vuex", icon: "https://via.placeholder.com/20" },
    ],
    jobDescription: [
      "Developed of high-performance web applications utilizing Nuxt.js, covering the application of core Vue.js concepts such as Vue Router, Vuex, and data reactivity",
      "Developed website interface with booking system and Midtrans payment integration",
      "Instrumental in building the Gompu application, applying the Scrum method in a collaborative team environment",
    ],
  },
];
